Egzakt\SystemBundle\Entity\BundleParam:
  type: entity
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
    value:
      type: string
      length: 255
  manyToOne:
    bundle:
      targetEntity: Egzakt\SystemBundle\Entity\Bundle
      inversedBy: params
      joinColumn:
        name: bundle_id
        referencedColumnName: id
        onDelete:  cascade