Unifik\SystemBundle\Entity\Section:
  type: entity
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    ordering:
      type: integer
      nullable: true
  repositoryClass: Unifik\SystemBundle\Entity\SectionRepository
  oneToMany:
    children:
      targetEntity: Unifik\SystemBundle\Entity\Section
      mappedBy: parent
      orderBy: { ordering: ASC }
    texts:
      targetEntity: Unifik\SystemBundle\Entity\Text
      mappedBy: section
    sectionNavigations:
      targetEntity: Unifik\SystemBundle\Entity\SectionNavigation
      mappedBy: section
      cascade: [persist]
      orphanRemoval: true
    mappings:
      targetEntity: Unifik\SystemBundle\Entity\Mapping
      mappedBy: section
      cascade: [persist]
  manyToOne:
    parent:
      targetEntity: Unifik\SystemBundle\Entity\Section
      inversedBy: children
      joinColumn:
        name: parent_id
        referencedColumnName: id
        onDelete: cascade
    app:
      targetEntity: Unifik\SystemBundle\Entity\App
      inversedBy:  sections
      joinColumn:
        name: app_id
        referencedColumnName: id
        onDelete: cascade
  manyToMany:
    roles:
      targetEntity: Unifik\SystemBundle\Entity\Role
      mappedBy: sections
