Egzakt\SystemBundle\Entity\SectionBundleParam:
  type: entity
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      length: 255
    value:
      type: string
      length: 255
  manyToOne:
    sectionBundle:
      targetEntity: Egzakt\SystemBundle\Entity\SectionBundle
      inversedBy:  params
      joinColumn:
        name: section_bundle_id
        referencedColumnName: id
        onDelete: cascade
