Egzakt\SystemBundle\Entity\SectionBundle:
  type: entity
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    ordering:
      type: integer
      nullable: true
  lifecycleCallbacks: {  }
  manyToOne:
    section:
      targetEntity: Egzakt\SystemBundle\Entity\Section
      inversedBy:  sectionBundles
      joinColumn:
        name: section_id
        referencedColumnName: id
        onDelete: cascade
    bundle:
      targetEntity: Egzakt\SystemBundle\Entity\Bundle
      inversedBy:  sectionBundles
      joinColumn:
        name: bundle_id
        referencedColumnName: id
        onDelete: cascade
  oneToMany:
    params:
      targetEntity: Egzakt\SystemBundle\Entity\SectionBundleParam
      mappedBy: sectionBundle