Unifik\SystemBundle\Entity\Text:
  type: entity
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    collapsable:
      type: boolean
    static:
      type: boolean
      default: false
    ordering:
      type: integer
      nullable: true
  repositoryClass: Unifik\SystemBundle\Entity\TextRepository
  manyToOne:
    section:
      targetEntity: Unifik\SystemBundle\Entity\Section
      inversedBy:   texts
      joinColumn:
        name: section_id
        referencedColumnName: id
        onDelete:  cascade