egzakt_system_frontend_home:
    pattern:  /
    defaults: { _controller: "EgzaktSystemBundle:Frontend/Home:index" }

egzakt_system_frontend_text:
    pattern:  /{sectionsPath}
    defaults: { _controller: "EgzaktSystemBundle:Frontend/Text:index" }
