parameters:
#    egzakt_system.example.class: Egzakt\SystemBundle\Example

services:
#    egzakt_system.example:
#        class: %egzakt_system.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
